# path to sample information CSV file (columns: sample_name, run, R1, R2, replicate_name)
samples: config/test_info.csv

# output directory path
result_path: /storage/zhangkaiLab/hanlitian/macrophage/process/20251220_RNA

ref:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 100
  # Genome build
  build: GRCh38

# Resource paths
resources:
  star_index: /storage/zhangkaiLab/hanlitian/database/algin_ref/atac_pipeline/hg38/star
  gtf: /storage/zhangkaiLab/hanlitian/database/algin_ref/atac_pipeline/hg38/gencode.v38.basic.annotation.gtf
  fasta: /storage/zhangkaiLab/hanlitian/database/algin_ref/atac_pipeline/hg38/hg38.fa

# STAR alignment parameters
params:
  star:
    align:
      extra: "--outSAMtype BAM SortedByCoordinate --quantMode GeneCounts"
    index:
      extra: ""